export const USER_INPUT_CLIENT = 'USER_INPUT_CLIENT';
export const BLUR_INPUT_CLIENT = 'BLUR_INPUT_CLIENT';
export const FOCUS_INPUT_CLIENT = 'FOCUS_INPUT_CLIENT';
export const VALIDATE_FORM_CLIENT = 'VALIDATE_FORM_CLIENT';
export const CLEAN_UP_FORM_CLIENT = 'CLEAN_UP_FORM_CLIENT';
